
- name: mount shared prog dir
  mount:
    path: /usr/local
    src: rio:/usr/local
    fstype: nfs
    opts: rw,hard,rsize=8192,wsize=8192,timeo=14
    state: mounted
  when: "'controller' not in group_names"

- name: create U2 dir
  file: path={{ item }} state=directory owner=root mode=0755
  with_items:
    - /U2

- name: mount iscsi mpath dir
  mount:
    path: /U2
    src: rio:/U2
    fstype: nfs
    opts: rw,hard,rsize=8192,wsize=8192,timeo=14
    state: mounted
  when: "'controller' not in group_names"
