
- stat: path=/usr/local/fsl/bin
  register: fsl_bin

- name: copy fsl installer script
  copy: src=fslinstaller.py dest=/tmp owner=root group=root mode=0755
  when: not fsl_bin.stat.exists

- name: run install script
  shell: /tmp/fslinstaller.py -E -q -d /usr/local/fsl
  when: not fsl_bin.stat.exists

- stat: path=/usr/local/fsl/fslpython
  register: fsl_python

- name: install fslpython
  shell: /usr/local/fsl/etc/fslconf/fslpython_install.sh -f /usr/local/fsl
  when: not fsl_python.stat.exists


